//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_menu : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.menu_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean CloseMenu
        {
            get
            {
                return SteamVR_Actions.menu_CloseMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean BackUI
        {
            get
            {
                return SteamVR_Actions.menu_BackUI;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.menu_Haptic;
            }
        }
    }
}
