//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_graph : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Spin
        {
            get
            {
                return SteamVR_Actions.graph_Spin;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ChangeVars
        {
            get
            {
                return SteamVR_Actions.graph_ChangeVars;
            }
        }
        
        public virtual SteamVR_Action_Boolean Scale_Move
        {
            get
            {
                return SteamVR_Actions.graph_Scale_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenMenu
        {
            get
            {
                return SteamVR_Actions.graph_OpenMenu;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.graph_Haptic;
            }
        }
    }
}
